CC = gcc
CFLAGS = -Wall

SRCS = functions.c main.c
OBJS = $(SRCS:.c=.o)
EXEC = myprogram

$(EXEC): $(OBJS)
	$(CC) -c $(CFLAGS) -o $(EXEC) $(OBJS)

%.o: %.c
	$(CC) $(CFLAGS) -c $<

clean:
	rm -f $(OBJS) $(EXEC)
